"""empty message

Revision ID: 296ede85e79f
Revises: 1469789c2f40
Create Date: 2021-08-28 20:47:09.704650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296ede85e79f'
down_revision = '1469789c2f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'title')
    # ### end Alembic commands ###
